### ISSUE TITLE
not working on server

### ISSUE THREAD

**Issue by OrangeTurtle197** [PatchworkMC/patchwork-api#196]
[https://youtu.be/bqJEdmBlvKs](https://youtu.be/bqJEdmBlvKs)

**Comment by williambl** [comment]
Optifine is client-only (and is not recommended for use at all with patchwork, fabric, or forge) - does the server work without Optifine?

**Comment by florensie** [comment]
Also the patcher jar should not be in the mods folder. Did you patch the forge mods?

**Comment by OrangeTurtle197** [comment]
> Optifine is client-only (and is not recommended for use at all with patchwork, fabric, or forge) - does the server work without Optifine?

still no

**Comment by OrangeTurtle197** [comment]
> Also the patcher jar should not be in the mods folder. Did you patch the forge mods?

how do i do that?

**Comment by williambl** [comment]
> > Also the patcher jar should not be in the mods folder. Did you patch the forge mods?
> 
> how do i do that?

Open the patcher jar, select the input and output folders, and click the patch button.

**Comment by OrangeTurtle197** [comment]
> > > Also the patcher jar should not be in the mods folder. Did you patch the forge mods?
> > 
> > 
> > how do i do that?
> 
> Open the patcher jar, select the input and output folders, and click the patch button.

moving out the patcher jar didn't work, and it seems to only patch 1.14.4.

**Comment by famous1622** [comment]
> > > > Also the patcher jar should not be in the mods folder. Did you patch the forge mods?
> > > 
> > > 
> > > how do i do that?
> > 
> > Open the patcher jar, select the input and output folders, and click the patch button.
> 
> moving out the patcher jar didn't work, and it seems to only patch 1.14.4.

It does in fact only patch mods for 1.14.4. We're updating soon.

**Comment by OrangeTurtle197** [comment]
> > > > > Also the patcher jar should not be in the mods folder. Did you patch the forge mods?
> > > > 
> > > > 
> > > > how do i do that?
> > > 
> > > 
> > > Open the patcher jar, select the input and output folders, and click the patch button.
> > 
> > 
> > moving out the patcher jar didn't work, and it seems to only patch 1.14.4.
> 
> It does in fact only patch mods for 1.14.4. We're updating soon.

is it required to patch mods to make them work with the patchwork api?

**Comment by famous1622** [comment]
> > > > > > Also the patcher jar should not be in the mods folder. Did you patch the forge mods?
> > > > > 
> > > > > 
> > > > > how do i do that?
> > > > 
> > > > 
> > > > Open the patcher jar, select the input and output folders, and click the patch button.
> > > 
> > > 
> > > moving out the patcher jar didn't work, and it seems to only patch 1.14.4.
> > 
> > It does in fact only patch mods for 1.14.4. We're updating soon.
> 
> is it required to patch mods to make them work with the patchwork api?

Yes, it is.

**Comment by TheGlitch76** [comment]
The initial issue was resolved with https://github.com/PatchworkMC/patchwork-api/commit/3794f3a741a1a77d89cafc0c8dad2dd331a2ce22

**Comment by OrangeTurtle197** [comment]
> The initial issue was resolved with [3794f3a](https://github.com/PatchworkMC/patchwork-api/commit/3794f3a741a1a77d89cafc0c8dad2dd331a2ce22)

no jarfile, doesn't it require a jar? i don't have any knowledge of compiling jars.

**Comment by TheGlitch76** [comment]
Why don't you join our [discord](https://discord.gg/YYZtNBG), you'll have more people who are able to help you
