### ISSUE TITLE
Implement IShearable

### ISSUE THREAD

**Issue by coderbot16** [PatchworkMC/patchwork-api#2]
* Test Mod: https://www.curseforge.com/minecraft/mc-mods/sbm-wooden-shears
* Module: `patchwork-extensions-shearing`
* Forge Classes:
  * `net.minecraftforge.common.IShearable`
* Classes Patched:
  * `ShearsItem`, `SeagrassBlock`, `VineBlock`, `LeavesBlock`, `DeadBushBlock`, `FernBlock`, `ReplaceableTallPlantBlock`, `CobwebBlock`, `DispenserBehavior`, `SnowGolemEntity`, `MooshroomEntity`, `SheepEntity`

**Comment by martmists** [comment]
Suggestion: Test compatibility with Fabric mods such as [Mooblooms](https://www.curseforge.com/minecraft/mc-mods/mooblooms)

**Comment by coderbot16** [comment]
Mooblooms appears like it will not work with modded shears... Not sure how to fix this.
