### ISSUE TITLE
Support mods that use ForgeHooks, ForgeEventFactory, etc directly

### ISSUE THREAD

**Issue by coderbot16** [PatchworkMC/patchwork-api#21]
Some mods call these functions directly. Patchwork splits them up per module, so we'll need to have a separate module that implements the original Forge versions. Perhaps the module could be `patchwork-event-dispatcher`?

* [ ] [WaMod - MoreBlockVariants](https://www.curseforge.com/minecraft/mc-mods/wamod-more-block-variants)
  * [ ] `ForgeEventFactory#saplingGrowTree`

**Comment by kitlith** [comment]
Outdated issue, this has been implemented (and is even being revisited, heh.)
