### ISSUE TITLE
Crash with nothing

### ISSUE THREAD

**Issue by TeamRIS** [PatchworkMC/patchwork-api#227]
log: 13.01 05:20:00 [Server] main/INFO Loading for game Minecraft 1.16.4
13.01 05:20:00 [Server] ForkJoinPool-1-worker-2/WARN The mod "dwarfcoal" contains invalid entries in its mod json:
13.01 05:20:00 [Server] INFO - Unsupported root entry "side" at line 16 column 9
13.01 05:20:00 [Server] ForkJoinPool-1-worker-7/WARN The mod "shulkerboxtooltip" contains invalid entries in its mod json:
13.01 05:20:00 [Server] INFO - Unsupported root entry "licence" at line 8 column 12
13.01 05:20:00 [Server] ForkJoinPool-1-worker-4/WARN The mod "autoconfig1u" contains invalid entries in its mod json:
13.01 05:20:00 [Server] INFO - Unsupported root entry "$schema" at line 2 column 14
13.01 05:20:00 [Server] ForkJoinPool-1-worker-5/WARN The mod "libcd" contains invalid entries in its mod json:
13.01 05:20:00 [Server] INFO - Unsupported root entry "licence" at line 9 column 12
13.01 05:20:00 [Server] ForkJoinPool-1-worker-4/WARN The mod "autoconfig1u" contains invalid entries in its mod json:
13.01 05:20:00 [Server] INFO - Unsupported root entry "$schema" at line 2 column 14
13.01 05:20:00 [Server] ForkJoinPool-1-worker-1/WARN The mod "cardinal-components-base" contains invalid entries in its mod json:
13.01 05:20:00 [Server] INFO - Unsupported root entry "side" at line 8 column 11
13.01 05:20:00 [Server] ForkJoinPool-1-worker-1/WARN The mod "cardinal-components-entity" contains invalid entries in its mod json:
13.01 05:20:00 [Server] INFO - Unsupported root entry "side" at line 8 column 11
13.01 05:20:00 [Server] ForkJoinPool-1-worker-5/WARN The mod "autoconfig1u" contains invalid entries in its mod json:
13.01 05:20:00 [Server] INFO - Unsupported root entry "$schema" at line 2 column 14
13.01 05:20:00 [Server] ForkJoinPool-1-worker-4/WARN The mod "autoconfig1u" contains invalid entries in its mod json:
13.01 05:20:00 [Server] INFO - Unsupported root entry "$schema" at line 2 column 14
13.01 05:20:00 [Server] ForkJoinPool-1-worker-5/WARN The mod "autoconfig1u" contains invalid entries in its mod json:
13.01 05:20:00 [Server] INFO - Unsupported root entry "$schema" at line 2 column 14
13.01 05:20:00 [Server] ForkJoinPool-1-worker-7/WARN The mod "autoconfig1u" contains invalid entries in its mod json:
13.01 05:20:00 [Server] INFO - Unsupported root entry "$schema" at line 2 column 14
13.01 05:20:00 [Server] ForkJoinPool-1-worker-1/WARN The mod "autoconfig1u" contains invalid entries in its mod json:
13.01 05:20:00 [Server] INFO - Unsupported root entry "$schema" at line 2 column 14
13.01 05:20:00 [Server] ForkJoinPool-1-worker-6/WARN The mod "autoconfig1u" contains invalid entries in its mod json:
13.01 05:20:00 [Server] INFO - Unsupported root entry "$schema" at line 2 column 14
13.01 05:20:00 [Server] ForkJoinPool-1-worker-6/WARN The mod "cardinal-components-base" contains invalid entries in its mod json:
13.01 05:20:00 [Server] INFO - Unsupported root entry "side" at line 8 column 11
13.01 05:20:00 [Server] ForkJoinPool-1-worker-4/WARN The mod "cardinal-components-entity" contains invalid entries in its mod json:
13.01 05:20:00 [Server] INFO - Unsupported root entry "side" at line 8 column 11
13.01 05:20:00 [Server] main/WARN Warnings were found! 
13.01 05:20:00 [Server] INFO - Conflicting versions found for fabric-networking-v0: used 0.1.10+e00ecb5fa7, also found 0.1.10+e00ecb5f95, 0.1.10+e00ecb5f3a
13.01 05:20:00 [Server] INFO - Conflicting versions found for fabric-key-binding-api-v1: used 1.0.1+730711c63a, also found 1.0.1+730711c6a7
13.01 05:20:00 [Server] INFO - Conflicting versions found for fabric-resource-loader-v0: used 0.3.1+facf3bbf3a, also found 0.3.1+facf3bbf95
13.01 05:20:00 [Server] INFO - Conflicting versions found for fabric-lifecycle-events-v1: used 1.2.0+74cc3b203a, also found 1.2.0+74cc3b2095, 1.2.0+74cc3b20a7
13.01 05:20:00 [Server] INFO - Conflicting versions found for fabric-events-lifecycle-v0: used 0.2.0+16acbe5b3a, also found 0.2.0+16acbe5ba7
13.01 05:20:00 [Server] main/INFO [FabricLoader] Loading 171 mods: fallflyinglib@1.1.0, fabric-keybindings-v0@0.2.0+3fa9f7c53a, roughlyenoughitems-api@5.8.3, patchwork-api-base@0.1.1+e4888677, ezpas@1.2.3-1.16.2, fabricloader@0.10.6+build.214, trinkets@2.6.7, patchwork-model-loader@0.2.3+e4888677, artifice@0.13.1+1.16.2-rc1, healthoverlay@3.6.12, kibe@1.5.2-BETA, patchwork-data-generators@0.3.1+e4888677, betternether@5.0.3, patchwork-recipes@0.3.1+e4888677, fabric-game-rule-api-v1@1.0.3+a4467d2a3a, patchwork-events-rendering@0.3.3+e4888677, staffofbuilding@1.2.3-1.16.2, fabric-api-base@0.2.0+9f0fb4b83a, reborncore@4.6.1+build.97, xaeroworldmap@1.11.0, jumpoverfences@1.16-0.0.3, patchwork-extensions-block@0.5.0+e4888677, fiber@0.23.0-1, patchwork-level-generators@0.3.1+e4888677, roughlyenoughresources@2.1.2, org_jetbrains_kotlin_kotlin-stdlib@1.4.0, playerabilitylib@1.2.1, patchwork@0.10.0, fabric-blockrenderlayer-v1@1.1.4+c6a8ea893a, villagerhats@fabric-1.16.4-1.0.1, mo_glass@1.5-MC1.16.4, patchwork-loot@0.3.1+e4888677, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.4.0, patchwork-extensions-item@0.4.1+e4888677, fabric@0.25.4+1.16, respawnablepets@1.16.4-1, patchwork-networking@0.4.0+f04a2d53, fabric-networking-v0@0.1.10+e00ecb5fa7, fabric-screen-handler-api-v1@1.1.0+872498413a, tk_valoeghese_zoesteriaconfig@1.3.2, repurposed_structures@1.16.3-1.6.9, patchwork-capabilities@0.5.0+e4888677, modmenu@1.14.8+build.12, greater_eye@1.1.3, blockshifter@1.3.2+fabric-1.16.4, phosphor@0.6.0+build.7, fabric-tool-attribute-api-v1@1.2.5+c93221003a, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.4.0, roughlyenoughitems-runtime@5.8.3, angerable-patch@1.0.0-1.16.1, bebooks@1.1.4, cloth-client-events-v0@1.4.5, voyager@1.0.0, fabric-events-interaction-v0@0.4.1+f8ac1db23a, fabric-crash-report-info-v1@0.1.2+b7f9825d3a, identity@1.10.2-beta-1.16.3, patchwork-items@0.1.1+e4888677, fabric-language-kotlin@1.4.0+build.1, fabric-key-binding-api-v1@1.0.1+730711c63a, mousewheelie@1.5.10+mc1.16.4, flan@1.16.2-1.1.4, fabric-language-scala@0.3.2.12, cloth-config2@4.8.3, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.3.9, fabric-resource-loader-v0@0.3.1+facf3bbf3a, chainmail@0.5.0, org_jetbrains_kotlin_kotlin-reflect@1.4.0, expandedstorage@5.6.31, patchwork-fml@0.5.0+e4888677, worldedit@7.2.0+a51fa43, cardinal-components-entity@2.7.2, patchwork-resource@0.2.1+e4888677, libblockattributes_fluids@0.8.3-pre.3, magna@1.4.2-1.16.2, fabric-commands-v0@0.2.0+52d308363a, fabric-registry-sync-v0@0.6.1+a4467d2a3a, adorn@1.12.0+1.16.4, cardinal-components-base@2.7.2, patchwork-biomes@0.3.1+e4888677, fabric-mining-levels-v0@0.1.2+b764ce993a, fabric-item-groups-v0@0.2.1+a4467d2a3a, fabric-models-v0@0.1.1+f8ac1db23a, shulkerboxtooltip@2.3.3+1.16.4, org_jetbrains_annotations@20.0.0, patchwork-registries@0.4.1+e4888677, truerooms@1.0.3, lithium-api@0.6.0, fabric-renderer-api-v1@0.3.3+a4467d2a3a, dwarfcoal@1.16.2-1.0.0, inventorysorter@1.7.4-1.16, patchwork-dispatcher@0.5.0+e4888677, libcd@3.0.3+1.16.3, patchwork-events-lifecycle@0.3.2+e4888677, patchwork-networking-messages@0.3.2+e4888677, mycommands@1.16.1-17, vanillaexcavators@1.1.0, fabric-structure-api-v1@1.1.0+f8ac1db23a, patchwork-extensions@0.3.1+e4888677, simpleteleporters@2.2.1, fabric-containers-v0@0.1.8+045df74f3a, lithium@0.6.0, fabric-object-builder-api-v1@1.9.2+a89534ab3a, patchwork-events-entity@0.7.0+e4888677, ringsofascension@1.1.1, waystones@1.0.9, fabric-rendering-data-attachment-v1@0.1.4+f8ac1db23a, fabric-textures-v0@1.0.5+a4467d2a3a, com_electronwill_night-config_core@3.6.2, linkart@unspecified, olifantenpad@1.0.0, patchwork-extensions-bakedmodel@0.1.0+ec08e71c, fabric-rendering-fluids-v1@0.1.12+f8ac1db23a, patchwork-events-world@0.5.0+e4888677, allstackable@1.2.6, glassdoor@1.5.0-1.16, fabric-lifecycle-events-v1@1.2.0+74cc3b203a, fabric-renderer-registries-v1@2.2.0+f8ac1db23a, fabric-loot-tables-v1@1.0.1+432ea1883a, dynamicfps@1.2.1, carpet@1.4.12, fabric-particles-v1@0.2.2+fb0d9b0e3a, libblockattributes_core@0.8.3-pre.3, patchwork-tags@0.1.1+e4888677, patchwork-gui@0.3.1+e4888677, patchwork-events-input@0.3.1+e4888677, minecraft@1.16.4, fabric-networking-blockentity-v0@0.2.5+b50ffc7b3a, roughlyenoughitems-default-plugin@5.8.3, woods_and_mires@1.0.3+1.16.3, jankson@3.0.1+j1.2.0, cloth-basic-math@0.5.1, fabric-command-api-v1@1.0.9+a4467d2a3a, patchwork-fake-players@0.1.1+e4888677, patchwork-eventbus@0.2.0, amecsapi@1.1.1+mc1.16-rc1, fabric-renderer-indigo@0.4.3+a4467d2a3a, patchwork-extensions-blockentity@0.2.0+e4888677, io_github_onyxstudios_cardinal-components-api@2.7.1, com_electronwill_night-config_toml@3.6.2, patchwork-vanilla-patches@0.3.1+e4888677, fabric-item-api-v1@1.2.0+f8ac1db23a, roughlyenoughitems@5.8.3, kyrptconfig@1.1.2-1.16, libgui@3.1.0+1.16.3, xaerominimap@20.27.2, patchwork-extensions-entity@0.1.0+09451ec1, fabric-rendering-v0@1.1.1+f8ac1db23a, croptopia@1.0.5-1.16.3-FABRIC, fabric-rendering-v1@1.3.1+f8ac1db23a, givemehats@1.2.8, winged@1.16.2-1.4.1, autoconfig1u@3.3.1, patchwork-extensions-shearing@0.3.1+e4888677, fabric-content-registries-v0@0.1.9+059ea8663a, fabric-tag-extensions-v0@1.0.3+ac8e8c593a, blue_endless_jankson@+, fabric-biome-api-v1@3.0.0+8367596d3a, patchwork-key-bindings@0.2.1+e4888677, appleskin@1.0.11, patchwork-tooltype@0.3.1+e4888677, byg@1.1.2, carrier@1.4.0, fabric-events-lifecycle-v0@0.2.0+16acbe5b3a, patchwork-enum-hacks@0.3.1+e4888677, betterend@0.6.2-beta, fabric-object-builders-v0@0.7.1+a4467d2a3a, team_reborn_energy@0.1.0, tweed@3.0.0-beta.20, secretrooms@0.9.2+1.16.2, org_yaml_snakeyaml@1.25, patchwork-god-classes@0.4.0+e4888677
13.01 05:20:00 [Server] main/WARN Mod `villagerhats` (fabric-1.16.4-1.0.1) does not respect SemVer - comparison support is limited.
13.01 05:20:00 [Server] main/WARN Mod `fabric-language-scala` (0.3.2.12) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
13.01 05:20:00 [Multicraft] Server already running
13.01 05:20:00 [Multicraft] Server ran command Start
13.01 05:20:01 [Multicraft] Skipped 3 lines due to rate limit (40/s)
13.01 05:20:01 [Server] main/WARN Reference map 'give-me-hats-1.16-refmap.json' for givemehats.mixins.json could not be read. If this is a development environment you can ignore this message
13.01 05:20:03 [Server] main/INFO Loaded configuration file for Lithium: 63 options available, 0 override(s) found
13.01 05:20:03 [Server] main/WARN Reference map 'ezpas-refmap.json' for ezpas.mixins.json could not be read. If this is a development environment you can ignore this message
13.01 05:20:03 [Server] main/WARN @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-v0.mixins.json:MixinEntityTracker and should be specified in value
13.01 05:20:04 [Server] main/WARN Error loading class: net/minecraft/class_2869 (java.lang.ClassNotFoundException: net/minecraft/class_2869)
13.01 05:20:04 [Server] main/WARN @Mixin target net.minecraft.class_2869 was not found patchwork-extensions.mixins.json:MixinDimension
13.01 05:20:04 [Server] main/WARN Error loading class: net/minecraft/class_310 (java.lang.ClassNotFoundException: net/minecraft/class_310)
13.01 05:20:04 [Server] main/WARN @Mixin target net.minecraft.class_310 was not found patchwork-extensions.mixins.json:MixinMinecraftClient
13.01 05:20:04 [Server] main/WARN Error loading class: net/minecraft/class_1942 (java.lang.ClassNotFoundException: net/minecraft/class_1942)
13.01 05:20:04 [Server] main/WARN @Mixin target net.minecraft.class_1942 was not found patchwork-level-generators.mixins.json:AccessorLevelGeneratorType
13.01 05:20:04 [Server] main/WARN Error loading class: net/minecraft/class_1942 (java.lang.ClassNotFoundException: net/minecraft/class_1942)
13.01 05:20:04 [Server] main/WARN @Mixin target net.minecraft.class_1942 was not found patchwork-level-generators.mixins.json:MixinLevelGeneratorType
13.01 05:20:04 [Server] main/WARN Error loading class: net/minecraft/class_2475 (java.lang.ClassNotFoundException: net/minecraft/class_2475)
13.01 05:20:04 [Server] main/WARN @Mixin target net.minecraft.class_2475 was not found patchwork-extensions-shearing.mixins.json:MixinShearableBlock
13.01 05:20:04 [Server] main/WARN Error loading class: net/minecraft/class_329 (java.lang.ClassNotFoundException: net/minecraft/class_329)
13.01 05:20:04 [Server] main/WARN @Mixin target net.minecraft.class_329 was not found identity.mixins.json:InGameHudMixin
13.01 05:20:04 [Server] main/WARN Error loading class: net/minecraft/class_3124$class_3125 (java.lang.ClassNotFoundException: net/minecraft/class_3124$class_3125)
13.01 05:20:04 [Server] main/WARN @Mixin target net.minecraft.class_3124$class_3125 was not found patchwork-enum-hacks.mixins.json:OreFeatureConfigTargetAccessor
13.01 05:20:04 [Server] main/WARN Error loading class: net/minecraft/class_3124$class_3125 (java.lang.ClassNotFoundException: net/minecraft/class_3124$class_3125)
13.01 05:20:04 [Server] main/WARN @Mixin target net.minecraft.class_3124$class_3125 was not found patchwork-enum-hacks.mixins.json:MixinOreFeatureConfigTarget
13.01 05:20:04 [Server] main/WARN Error loading class: net/minecraft/class_2248$class_2251 (java.lang.ClassNotFoundException: net/minecraft/class_2248$class_2251)
13.01 05:20:04 [Server] main/WARN @Mixin target net.minecraft.class_2248$class_2251 was not found patchwork-extensions-block.mixins.json:MixinBlockSettings
13.01 05:20:04 [Server] main/WARN Error loading class: net/minecraft/class_1969 (java.lang.ClassNotFoundException: net/minecraft/class_1969)
13.01 05:20:04 [Server] main/WARN @Mixin target net.minecraft.class_1969 was not found patchwork-registries.mixins.json:MixinBiomeSourceType
13.01 05:20:04 [Server] main/WARN Error loading class: net/minecraft/class_2798 (java.lang.ClassNotFoundException: net/minecraft/class_2798)
13.01 05:20:04 [Server] main/WARN @Mixin target net.minecraft.class_2798 was not found patchwork-registries.mixins.json:MixinChunkGeneratorType
13.01 05:20:04 [Server] main/ERROR patchwork-extensions-shearing.mixins.json:MixinDispenserBehavior: Super class 'net.minecraft.class_2969' of MixinDispenserBehavior was not found in the hierarchy of target class 'net/minecraft/class_2357$13'
13.01 05:20:04 [Server] INFO org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Super class 'net.minecraft.class_2969' of MixinDispenserBehavior was not found in the hierarchy of target class 'net/minecraft/class_2357$13'
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard.validate(MixinInfo.java:590) ~[fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinInfo$State.validate(MixinInfo.java:326) ~[fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinInfo.validate(MixinInfo.java:904) ~[fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:674) [fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:542) [fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) [fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) [fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-server-launch.jar:?]
13.01 05:20:04 [Multicraft] Skipped 13 lines due to rate limit (40/s)
13.01 05:20:04 [Server] main/FATAL Mixin apply failed patchwork-events-entity.mixins.json:MixinPlayerEntity -> net.minecraft.class_1657: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on hookHandleFallDamage could not find any targets matching 'Lnet/minecraft/class_1657;method_5747(FF)V' in net.minecraft.class_1657. Using refmap patchwork-events-entity-refmap.json [PREINJECT Applicator Phase -> patchwork-events-entity.mixins.json:MixinPlayerEntity -> Prepare Injections ->  -> handler$zba000$hookHandleFallDamage(FFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
13.01 05:20:04 [Server] INFO org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on hookHandleFallDamage could not find any targets matching 'Lnet/minecraft/class_1657;method_5747(FF)V' in net.minecraft.class_1657. Using refmap patchwork-events-entity-refmap.json [PREINJECT Applicator Phase -> patchwork-events-entity.mixins.json:MixinPlayerEntity -> Prepare Injections ->  -> handler$zba000$hookHandleFallDamage(FFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572) ~[fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288) ~[fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275) ~[fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267) ~[fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_272]
13.01 05:20:04 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_272]
13.01 05:20:04 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_272]
13.01 05:20:04 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_272]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140) ~[fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624) ~[fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247) ~[fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_272]
13.01 05:20:04 [Server] INFO at net.minecraft.class_128.handler$bgg000$gameStarted(class_128.java:1016) [intermediary-server.jar:?]
13.01 05:20:04 [Server] INFO at net.minecraft.class_128.method_24305(class_128.java:303) [intermediary-server.jar:?]
13.01 05:20:04 [Server] INFO at net.minecraft.server.Main.main(Main.java:85) [intermediary-server.jar:?]
13.01 05:20:04 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_272]
13.01 05:20:04 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_272]
13.01 05:20:04 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
13.01 05:20:04 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
13.01 05:20:04 [Server] INFO at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric-server-launch.jar:?]
13.01 05:20:04 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_272]
13.01 05:20:04 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_272]
13.01 05:20:04 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
13.01 05:20:04 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]

pls help.

**Comment by TheGlitch76** [comment]
The current release of Patchwork-API does not run on 1.16.4.
No supported builds of Patchwork are available right now, you must compile them from source.
