### ISSUE TITLE
Gradle tries to run 12 instances of Minecraft at once

### ISSUE THREAD

**Issue by BitBlitObviMormon** [PatchworkMC/patchwork-api#228]
I was trying to add support for SoundPhysics, but when I test it with "./gradlew build" followed by "./gradlew runClient" I get 12 Minecraft clients all starting up at once using up all of my computer's resources. The first time I ran this it froze forcing me to hard reset my computer. The second time worked all right so long as I quickly crashed 11 of the instances of Minecraft with Task Manager.
I am using JDK 1.8.0.271 on a 64-bit Windows 10 computer. I am also using a clean git clone with no files changed as of yet on the latest commit (3ac24d3602a1f7ed214c003284205e6ebdbac5ea).

The stdout and stderr output from gradle:
[output.txt](https://github.com/PatchworkMC/patchwork-api/files/5817533/output.txt)

**Comment by ramidzkh** [comment]
Try using `./gradlew :runClient` so it doesn't invoke all of its subprojects

**Comment by TheGlitch76** [comment]
This is a Loom "feature" in multiproject builds, ramid's solution is the way to do it.
Alternatively, use the run configs in your IDE.
