### ISSUE TITLE
Build not working?

### ISSUE THREAD

**Issue by GamingInfinite** [PatchworkMC/patchwork-api#233]
- [x]  I understand that the latest version of Patchwork released on Github Releases is not supported, and I have compiled the version the bug is found on from the source code.
- [x] I understand that a crash report that includes the line "Patchwork mod [modid] tried to access an unimplemented [...]" is not a bug, but instead a report that a mod is missing a feature. I will not open an issue for crash reports that report unimplemented features.
- [x] I understand if I do not confirm these things my issue will be closed as invalid.

**Describe the bug**
After building the latest 1.16.x version, I tried running it with a patched mod in fabric (with fabric API), and it crashed outright.  From what I can gather it seems to be a problem with my build of patchwork so if anyone has a 1.16.x build that they got working they can send so I can test the mod I patched, that'd be great.

**Expected behavior**
For it to at least get to mod loading before crashing.

**Screenshots or Crash Report**
[crash report](https://pastebin.com/WLdyfBk0)

**Additional context**
I had fabric API in there as well, but even with the rest of my mods it had the same problem as with none so idk.

**Comment by TheGlitch76** [comment]
This does not look like it is the latest 1.16 version of Patchwork API--I see some mods in there that are [not defined in the settings.gradle yet](https://github.com/PatchworkMC/patchwork-api/blob/1.16.x/settings.gradle)

Perhaps you're using the wrong branch?

**Comment by GamingInfinite** [comment]
I downloaded the one in releases, if the current source is different I'll try that.

**Comment by cittyinthecloud** [comment]
You need to build yourself. The version in releases is very outdated.

**Comment by TheGlitch76** [comment]
> I understand that the latest version of Patchwork released on Github Releases is not supported, and I have compiled the version the bug is found on from the source code.

As stated here :P

I'll clarify in the template that it's from the *latest* source code, not the one in releases, since I see that's kind of confusing.

**Comment by GamingInfinite** [comment]
sorry yeah I assumed the download from releases was current.  specially since it is just source code so sorry :p
