### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by IceCryptonym** [PatchworkMC/patchwork-api#26]
I would like to contribute but it is unclear what I'm suppose to do to set this up. I put the patchwork-api into mods folder and I'm getting an error.
`java.lang.NoClassDefFoundError: net/minecraftforge/eventbus/api/Event`

Am I missing something?

**Comment by shedaniel** [comment]
EventBus is not included in the api jar (yet), please get it.

also we should really jij it.
