### ISSUE TITLE
Jcenter issue

### ISSUE THREAD

**Issue by natanfudge** [PatchworkMC/patchwork-api#28]
Please click the button

**Comment by coderbot16** [comment]
Does it take days to approve every single time?

**Comment by TheGlitch76** [comment]
@coderbot16 what's happening with this?

**Comment by coderbot16** [comment]
I did it once, but is it necessary for all releases?

**Comment by natanfudge** [comment]
No

**Comment by coderbot16** [comment]
Should be fixed, please verify @natanfudge
