### ISSUE TITLE
Outline for LivingFallEvent and PlayerFlyableFallEvent

### ISSUE THREAD

**Issue by coderbot16** [PatchworkMC/patchwork-api#29]
Mod: [SBM Infinite Falling](https://www.curseforge.com/minecraft/mc-mods/sbm-infinite-falling)

* [ ] `LivingFallEvent`
  * Dispatched in `ForgeHooks#onLivingFall`
  * Patches: `LivingEntity`
* [ ] `PlayerFlyableFallEvent`
  * Dispatched in `ForgeEventFactory#onPlayerFall`
  * Patches: `PlayerEntity`

**Comment by coderbot16** [comment]
@IceCryptonym want me to assign you to this?

**Comment by IceCryptonym** [comment]
Yeah, that would be great.

**Comment by coderbot16** [comment]
There you go :+1:

**Comment by coderbot16** [comment]
IceCryptonym just dropped off the face of the earth, if anyone else wants to do this they're welcome to. I don't have the code archived anywhere so you'll probably have to redo it!

**Comment by IceCryptonym** [comment]
This issue can be closed.

**Comment by coderbot16** [comment]
Thanks!
