### ISSUE TITLE
Forge Capabilities support

### ISSUE THREAD

**Issue by coderbot16** [PatchworkMC/patchwork-api#3]
@ramidzkh is looking into this

**Comment by coderbot16** [comment]
Required for supporting [SBM Jukebox](https://www.curseforge.com/minecraft/mc-mods/sbm-jukebox)

**Comment by TheGlitch76** [comment]
Has this been implemented in Patcher yet? (cc @ramidzkh @coderbot16)

**Comment by coderbot16** [comment]
CapabilityInject is not yet implemented in patcher, but that seems more proper as an issue on the Patcher repo.

**Comment by ramidzkh** [comment]
CapabilityInject can be piggy-backed of the object holder system but that's probably going to add unnecessary amounts of some developer debt

**Comment by coderbot16** [comment]
Closing in favor of https://github.com/PatchworkMC/patchwork-patcher/issues/50
