### ISSUE TITLE
Crashes for Bones

### ISSUE THREAD

**Issue by florensie** [PatchworkMC/patchwork-api#31]
[CurseForge](https://www.curseforge.com/minecraft/mc-mods/bones/)
[GitHub](https://github.com/ochotonida/bones)
- [x] ~`... overrides final method getLootTable.()Lnet/minecraft/util/Identifier;`
[crash-2020-01-19_17.23.13-client.txt](https://github.com/PatchworkMC/patchwork-api/files/4083885/crash-2020-01-19_17.23.13-client.txt)~
Probably an issue with my original forge jar, can't seem to be able to replicate it
- [ ] `java.lang.IllegalAccessError: tried to access method net.minecraft.entity.SpawnRestriction.setRestrictions(...`
[crash-2020-01-22_15.01.49-client.txt](https://github.com/PatchworkMC/patchwork-api/files/4097675/crash-2020-01-22_15.01.49-client.txt)
- [x] `java.lang.NoSuchMethodError: net.minecraft.sound.SoundEvent.setRegistryName(...`
[crash-2020-01-19_23.39.51-client.txt](https://github.com/PatchworkMC/patchwork-api/files/4083895/crash-2020-01-19_23.39.51-client.txt)
- [x] `java.lang.NoClassDefFoundError: net/minecraftforge/fml/DeferredWorkQueue`
[crash-2020-01-19_23.49.51-client.txt](https://github.com/PatchworkMC/patchwork-api/files/4083896/crash-2020-01-19_23.49.51-client.txt)
- [x] `java.lang.NoClassDefFoundError: net/minecraftforge/fml/client/registry/IRenderFactory`
[crash-2020-01-19_23.54.53-client.txt](https://github.com/PatchworkMC/patchwork-api/files/4083898/crash-2020-01-19_23.54.53-client.txt)

**Comment by TheGlitch76** [comment]
All features have been added in this list
