### ISSUE TITLE
Implement GatherDataEvent

### ISSUE THREAD

**Issue by coderbot16** [PatchworkMC/patchwork-api#37]
Required for https://www.curseforge.com/minecraft/mc-mods/comforts

Also required by *many* other mods: https://github.com/search?q=GatherDataEvent&type=Code

**Comment by coderbot16** [comment]
Note: Should we try to reimplement all of this, or just the stubs to get mods to run? Technically it isn't needed for just running mods, since this is part of the compilation.

**Comment by Rongmario** [comment]
Stubs is enough, I can't think of any reasons why GatherDataEvent would be needed after compilation

**Comment by coderbot16** [comment]
It's possible that patchwork-api will eventually be used as an aid for porting Forge mods, so I think it would probably be best to keep the implementation. I don't think that the Forge data generators would need *too* much change to work in Fabric, they're certainly tied less to Minecraft code than other parts of Forge.

**Comment by Rongmario** [comment]
Yeah I went through it quickly, it also depends what patchwork would do with forge's lifecycle stuff on a whole, but keeping the implementation of GatherDataEvent is fine, other than dispatching it as a lifecycle event, it really just runs in net.minecraft.data.Main's main method with necessary flags.

**Comment by coderbot16** [comment]
Currently we have the core lifecycle event dispatch in patchwork-dispatcher, however actually dispatching the event probably isn't strictly necessary at the moment.

**Comment by l-Luna** [comment]
perhaps check if this works, now that GatherDataEvent has been implemented.

**Comment by TheGlitch76** [comment]
Resolved in https://github.com/PatchworkMC/patchwork-api/commit/4f71b11f3acf6162a699be30d6e6d29b8b44504d
