### ISSUE TITLE
Outline for LivingAttackEvent, LivingSpawnEvent, LivingHurtEvent, LivingFallEvent, and PlayerFlyableFallEvent

### ISSUE THREAD

**Issue by coderbot16** [PatchworkMC/patchwork-api#4]
All of these events should go in `patchwork-events-entity`.

* Mod: [SBM Punt Animal](https://www.curseforge.com/minecraft/mc-mods/sbm-punt-animal)
  * `LivingAttackEvent`
    * Dispatched in `ForgeHooks#onPlayerAttack` and `ForgeHooks#onLivingAttack`
    * Patches: `PlayerEntity`, `ClientPlayerEntity`, `OtherClientPlayerEntity`, `LivingEntity`
* Mod: [SBM Dual Wither](https://www.curseforge.com/minecraft/mc-mods/sbm-dual-wither)
  * `LivingSpawnEvent`
    * `LivingSpawnEvent.CheckSpawn`
      * Dispatched in `ForgeEventFactory#canEntitySpawn`, `ForgeHooks#canEntitySpawn`
      * Interfaces: `IForgeBlock#canCreatureSpawn`
      * Patches: `SpawnHelper`, `MobSpawnerLogic`
    * `LivingSpawnEvent.SpecialSpawn`
      * Dispatched in `ForgeEventFactory#doSpecialSpawn`
      * Patches: `SpawnHelper`, `EntityType`
    * `LivingSpawnEvent.AllowDespawn`
      * Dispatched in `ForgeEventFactory#canEntityDespawn`
      * Patches: `MobEntity`
  * `LivingHurtEvent`
    * Dispatched in `ForgeHooks#onLivingHurt`
    * Patches: `LivingEntity`, `PlayerEntity`
* Mod: [SBM Infinite Falling](https://www.curseforge.com/minecraft/mc-mods/sbm-infinite-falling)
  * `LivingFallEvent`
    * Dispatched in `ForgeHooks#onLivingFall`
    * Patches: `LivingEntity`
  * `PlayerFlyableFallEvent`
    * Dispatched in `ForgeEventFactory#onPlayerFall`
    * Patches: `PlayerEntity`

**Comment by Nuclearfarts** [comment]
note: SBM Dual Wither is broken and crashes on launch on vanillaforge.

**Comment by coderbot16** [comment]
Splitting off the fall events into https://github.com/PatchworkMC/patchwork-api/issues/29, most of the other events were implemented in https://github.com/PatchworkMC/patchwork-api/pull/25.
