### ISSUE TITLE
FMLLoadCompleteEvent sent before Minecraft.init has returned

### ISSUE THREAD

**Issue by ZNixian** [PatchworkMC/patchwork-api#85]
In Forge, `FMLLoadCompleteEvent` is sent well after `Minecraft.init` has returned. That method sets up a lot of stuff, which mods (such as Curios) may then access.

In Patchwork currently it's sent during initialisation, before anything in `Minecraft.init` has run.

**Comment by TheGlitch76** [comment]
This happens on the dedi server as well--should be done there too.
