### ISSUE TITLE
Required features for Classic Bars

### ISSUE THREAD

**Issue by coderbot16** [PatchworkMC/patchwork-api#9]
[CurseForge](https://www.curseforge.com/minecraft/mc-mods/classic-bars)

"a nice test for screen render events"

* [x] `patchwork-registries`
  * [x] ForgeRegistries
* [x] `patchwork-fml`
  * [x] ObfuscationReflectionHelper (related issue: https://github.com/PatchworkMC/patchwork-patcher/issues/5)
  * [x] ModList
  * [x] ConfigChangedEvent
* [ ] `patchwork-rendering`
  * [ ] ForgeIngameGui
  * [ ] RenderGameOverlayEvent
* [x] `patchwork-networking`
  * [x] NetworkRegistry
  * [x] SimpleChannel
  * [x] NetworkDirection
  * [x] NetworkEvent.Context
* [x] `patchwork-events-entity`
  * [x] PlayerEvent.PlayerLoggedInEvent
  * [x] LivingEvent.LivingUpdateEvent

**Comment by TheGlitch76** [comment]
Closing because we have moved to 1.16
