### ISSUE TITLE
Required Features for Biomes O Plenty

### ISSUE THREAD

**Issue by valoeghese** [PatchworkMC/patchwork-api#98]
Please let me know any others!
What I know so far is that we need this

- [x] IPlantable
![image](https://user-images.githubusercontent.com/46117728/85247886-5a8bc600-b4a3-11ea-855b-4ed404df9669.png)
- [x] Tool Types (#73 does this stage)
![image](https://user-images.githubusercontent.com/46117728/85275046-e4538780-b4d3-11ea-9fcd-0e0f72715694.png)
- [ ] Block.Settings harvest level, which is what bop uses tool types for
![image](https://user-images.githubusercontent.com/46117728/86098369-1edba680-bb0a-11ea-8eac-83c5662d7ce9.png)

**Comment by valoeghese** [comment]
https://github.com/MinecraftForge/MinecraftForge/blob/1.15.x/patches/minecraft/net/minecraft/block/Block.java.patch#L262

**Comment by valoeghese** [comment]
How difficult would implementing harvestTool and harvestLevel be? If it’s not difficult I’ll probably make a pr myself

**Comment by valoeghese** [comment]
But that involves actually finding the patches

**Comment by TheGlitch76** [comment]
You can set up a Forge dev environment and use your IDE to figure out the call locations

**Comment by valoeghese** [comment]
Well yes I know, that’s what I did for chunk data event (which I’ve paused working on). It’s just I’ve been trying to spend less time programming lately and have a break

**Comment by valoeghese** [comment]
So I was only going to do it if it proved easy, but I was being a lazy prick and not bothering to do it myself
